{
    "timestamp": "2025-04-17 22:08:51",
    "client_ip": "127.0.0.1",
    "method": "GET",
    "url": "http://localhost:8000/posts/?skip=0&limit=100",
    "headers": {
        "host": "localhost:8000",
        "connection": "keep-alive",
        "sec-ch-ua-platform": "\"Windows\"",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36",
        "accept": "application/json",
        "sec-ch-ua": "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"YaBrowser\";v=\"25.2\", \"Yowser\";v=\"2.5\"",
        "sec-ch-ua-mobile": "?0",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "cors",
        "sec-fetch-dest": "empty",
        "referer": "http://localhost:8000/docs",
        "accept-encoding": "gzip, deflate, br, zstd",
        "accept-language": "ru,en;q=0.9"
    },
    "error_type": "OperationalError",
    "error_message": "(psycopg2.OperationalError) connection to server at \"62.109.26.235\", port 5432 failed: Connection refused (0x0000274D/10061)\n\tIs the server running on that host and accepting TCP/IP connections?\n\n(Background on this error at: https://sqlalche.me/e/20/e3q8)",
    "traceback": "Traceback (most recent call last):\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 146, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3298, in raw_connection\n    return self.pool.connect()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 713, in checkout\n    rec = pool._do_get()\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 675, in __init__\n    self.__connect()\n    ~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 901, in __connect\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\psycopg2\\__init__.py\", line 135, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at \"62.109.26.235\", port 5432 failed: Connection refused (0x0000274D/10061)\n\tIs the server running on that host and accepting TCP/IP connections?\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 214, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\concurrency.py\", line 37, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\anyio\\to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 2470, in run_sync_in_worker_thread\n    return await future\n           ^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 967, in run\n    result = context.run(func, *args)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\app\\routes.py\", line 136, in read_posts\n    posts = PostService.get_posts(db, skip=skip, limit=limit)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\app\\services\\post_service.py\", line 142, in get_posts\n    ).order_by(desc(Post.creation_date)).offset(skip).limit(limit).all()\n                                                                   ~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 2704, in all\n    return self._iter().all()  # type: ignore\n           ~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 2858, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n                                                  ~~~~~~~~~~~~~~~~~~~~^\n        statement,\n        ^^^^^^^^^^\n        params,\n        ^^^^^^^\n        execution_options={\"_sa_orm_load_options\": self.load_options},\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2365, in execute\n    return self._execute_internal(\n           ~~~~~~~~~~~~~~~~~~~~~~^\n        statement,\n        ^^^^^^^^^^\n    ...<4 lines>...\n        _add_event=_add_event,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2241, in _execute_internal\n    conn = self._connection_for_bind(bind)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2110, in _connection_for_bind\n    return trans._connection_for_bind(engine, execution_options)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<string>\", line 2, in _connection_for_bind\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 1189, in _connection_for_bind\n    conn = bind.connect()\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3274, in connect\n    return self._connection_cls(self)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 148, in __init__\n    Connection._handle_dbapi_exception_noconnection(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        err, dialect, engine\n        ^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2439, in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 146, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3298, in raw_connection\n    return self.pool.connect()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 713, in checkout\n    rec = pool._do_get()\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 675, in __init__\n    self.__connect()\n    ~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 901, in __connect\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\psycopg2\\__init__.py\", line 135, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"62.109.26.235\", port 5432 failed: Connection refused (0x0000274D/10061)\n\tIs the server running on that host and accepting TCP/IP connections?\n\n(Background on this error at: https://sqlalche.me/e/20/e3q8)\n"
}