{
    "timestamp": "2025-04-18 13:04:00",
    "client_ip": "127.0.0.1",
    "method": "GET",
    "url": "http://localhost:8000/posts/17",
    "headers": {
        "host": "localhost:8000",
        "connection": "keep-alive",
        "sec-ch-ua-platform": "\"Windows\"",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36",
        "accept": "application/json",
        "sec-ch-ua": "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"YaBrowser\";v=\"25.2\", \"Yowser\";v=\"2.5\"",
        "sec-ch-ua-mobile": "?0",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "cors",
        "sec-fetch-dest": "empty",
        "referer": "http://localhost:8000/docs",
        "accept-encoding": "gzip, deflate, br, zstd",
        "accept-language": "ru,en;q=0.9"
    },
    "error_type": "ResponseValidationError",
    "error_message": "1 validation errors:\n  {'type': 'missing', 'loc': ('response', 'tags', 0, 'tag_type', 'type_id'), 'msg': 'Field required', 'input': <app.models.models.TagType object at 0x0000022C9A362900>}\n",
    "traceback": "  + Exception Group Traceback (most recent call last):\n  |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 174, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 173, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Python313\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 175, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\app\\utils\\middleware.py\", line 17, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 153, in call_next\n    |     raise app_exc\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 140, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    |     await self.app(scope, receive, send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 327, in app\n    |     content = await serialize_response(\n    |               ^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<9 lines>...\n    |     )\n    |     ^\n    |   File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 176, in serialize_response\n    |     raise ResponseValidationError(\n    |         errors=_normalize_errors(errors), body=response_content\n    |     )\n    | fastapi.exceptions.ResponseValidationError: 1 validation errors:\n    |   {'type': 'missing', 'loc': ('response', 'tags', 0, 'tag_type', 'type_id'), 'msg': 'Field required', 'input': <app.models.models.TagType object at 0x0000022C9A362900>}\n    | \n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 173, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Python313\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 175, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\app\\utils\\middleware.py\", line 17, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 153, in call_next\n    raise app_exc\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 140, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 327, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<9 lines>...\n    )\n    ^\n  File \"D:\\\u041f\u0440\u043e\u0435\u043a\u0442\u044b\\Threads_Hack\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 176, in serialize_response\n    raise ResponseValidationError(\n        errors=_normalize_errors(errors), body=response_content\n    )\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'missing', 'loc': ('response', 'tags', 0, 'tag_type', 'type_id'), 'msg': 'Field required', 'input': <app.models.models.TagType object at 0x0000022C9A362900>}\n\n"
}